---
- name: installing packages
  hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: install packages
      yum:
        name: "{{ item }}"
      with_items:
        - git
        - httpd
    - name: starting httpd services
      service:
        name: httpd
        state: started

    - copy:
        src: /home/ansadmin/playbooks/users.yml
        dest: /var/www/html
