---
- name: creating files or directores
  hosts: all
  become: true
  gather_facts: no

  tasks: 
  - name: creating a file 
    file:
      path: /home/ec2-user/test1
      state: absent
      mode: 0755

