---
- name: install packages
  hosts: all
  become: true
  gather_facts: yes

  tasks:
  - name: install packages
    yum:
      name: ['telnet', 'tree', 'httpd']
      state: installed

  - name: uninstall packages
    yum:
      name: ['git', 'telnet']
      state: removed


